### PR TITLE
Musark 116

### PR DESCRIPTION
**Pull request by ellenjo**
This change is [Reviewable](https://reviewable.io/reviews/musit-norway/musit/36)

### CODE REVIEW

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 133
           

Complexity increasing per file
==============================
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  6
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  21
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala  5
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  4
- common/src/main/scala/no/uio/musit/microservices/common/extensions/PlayExtensions.scala  3
         

Clones added
============
- service_storage_admin/test/controllers/StorageUnitControllerSpec.scala  1
- service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  4
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  5
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala  2
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  2
- service_musit_thing/src/it/scala/MusitThing_TestSuite.scala  17
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/klaus-myrseth/musit/pullRequest?prid=246351&bid=3326252)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 135
           

Complexity increasing per file
==============================
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  6
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  21
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala  5
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  4
- common/src/main/scala/no/uio/musit/microservices/common/extensions/PlayExtensions.scala  3
         

Clones added
============
- service_storage_admin/test/controllers/StorageUnitControllerSpec.scala  1
- service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  4
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  5
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala  2
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  2
- service_musit_thing/src/it/scala/MusitThing_TestSuite.scala  17
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/klaus-myrseth/musit/pullRequest?prid=246351&bid=3326252)

**Comment by jarlah** [comment]
Reviewed 4 of 15 files at r1, 2 of 9 files at r3, 2 of 7 files at r4, 2 of 8 files at r5, 1 of 4 files at r6, 4 of 7 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 28 unresolved discussions.

---

_[common/src/main/scala/no/uio/musit/microservices/common/extensions/FunctorExtensions.scala, line 1 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0RenEF4dKTiRxZAZZ:-KJ0RenEF4dKTiRxZAZ_:-194398873) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/common/src/main/scala/no/uio/musit/microservices/common/extensions/FunctorExtensions.scala#L1)):_

> ``` Scala
> /*
> ```

Remove this file. Concepts not currently in use can live in a fork or similar places

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 26 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0SCe3gahLhyoEGgHl:-KJ0SCe48OsmpdOjHoJy:2125390435) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L26)):_

> ``` Scala
> 
>   def linkText(id: Option[Long]) = {
>     assert(id.isDefined)
> ```

No, no. This is an excellent place to return a differentiated result, for ex Either, where the left side is a validation issue and the right side is the value. Because assert will fail the entire service, and it shouldn't when its just invalid data. Optionally make the calling function call this function with the unwrapped Long value instead of option

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 48 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0SWtJcj8NFJsQg4Fn:-KJ0SWtJcj8NFJsQg4Fo:424715473) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L48)):_

> ``` Scala
> 
>   def insert(storageUnit: StorageUnit): Future[StorageUnit] = {
>     println(s"Før insert Unit: $storageUnit")
> ```

comment or remove this line

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 53 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0SaXbPJ-EiUHTmdZF:-KJ0SaXcoxSZmV-Tej0z:1858219863) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L53)):_

> ``` Scala
>     val action = insertQuery += storageUnit
>     val result = db.run(action)
>     result.map {
> ```

remove this map and println

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 61 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0SjcAjOPUelWwH2y5:-KJ0SjcAjOPUelWwH2y6:727708933) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L61)):_

> ``` Scala
> 
>   def insertRoomOnly(storageRoom: StorageRoom): Future[StorageRoom] = {
>     println(s"Før insert Rom: $storageRoom")
> ```

comment or remove 

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 62 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0T8MmXRsPgCmY6SAe:-KJ0T8MmXRsPgCmY6SAf:788692661) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L62)):_

> ``` Scala
>   def insertRoomOnly(storageRoom: StorageRoom): Future[StorageRoom] = {
>     println(s"Før insert Rom: $storageRoom")
>     val insertQuery = RoomTable //returning RoomTable.map(_.id) into ((storageRoom, id) => storageRoom.copy(id = id, links = Seq(LinkService.self(s"/v1/$id"))))
> ```

remove comment or move it

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 65 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0Sz4FvyBmZUun4ZJE:-KJ0Sz4FvyBmZUun4ZJF:-1126915138) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L65)):_

> ``` Scala
>     val action = insertQuery += (storageRoom.copy(links = linkText(storageRoom.id)))
>     val result = db.run(action)
>     result.map {
> ```

remove this map and println, or comment it

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 82 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0Shxp0IQD0rPDw7eX:-KJ0Shxp0IQD0rPDw7eY:-1777640837) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L82)):_

> ``` Scala
> 
>   def insertBuildingOnly(storageBuilding: StorageBuilding): Future[StorageBuilding] = {
>     println(s"Før insert: $storageBuilding")
> ```

comment or remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 83 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0Tg_V37qnTqFJGThB:-KJ0Tg_V37qnTqFJGThC:1228524195) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L83)):_

> ``` Scala
>   def insertBuildingOnly(storageBuilding: StorageBuilding): Future[StorageBuilding] = {
>     println(s"Før insert: $storageBuilding")
>     val insertQuery = BuildingTable //returning BuildingTable.map(_.id) into
> ```

remove comments or move them

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 87 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0SgH3QhN0uWiVjVTO:-KJ0SgH3QhN0uWiVjVTP:1858219863) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L87)):_

> ``` Scala
>     val action = insertQuery += (storageBuilding.copy(links = linkText(storageBuilding.id)))
>     val result = db.run(action)
>     result.map {
> ```

remove this map and println

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 103 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0SnRPDMNmWHPUhnWk:-KJ0SnRPDMNmWHPUhnWl:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L103)):_

> ``` Scala
>   }
> 
>   /* def getDisplayID(id:Long) :Future[Option[String]] ={
> ```

remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 111 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0SoRPZSI55vXHm5-S:-KJ0SoRPZSI55vXHm5-T:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L111)):_

> ``` Scala
>   }
> 
>   /*def updateStorageNameByID(id: Long, storageName: String) = {
> ```

remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala, line 33 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0UZtF4RsVXJVUOOt7:-KJ0UZtF4RsVXJVUOOt8:1775510484) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala#L33)):_

> ``` Scala
> 
>   def getId: Long
>   /* def id: Long
> ```

remove this comment

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala, line 58 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0Uiis99fGrPFHPhHT:-KJ0Uiis99fGrPFHPhHU:-2134235649) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala#L58)):_

> ``` Scala
> 
> case class StorageRoom(id: Option[Long], sikringSkallsikring: Option[String], sikringTyverisikring: Option[String],
>     sikringBrannsikring: Option[String], sikringVannskaderisiko: Option[String], sikringRutineOgBeredskap: Option[String],
> ```

might be easier to read if aligned vertically instead. This applies to all places which have long constructors.

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala, line 17 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0UtSpNIeg_DOUrPUS:-KJ0UtSpNIeg_DOUrPUT:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala#L17)):_

> ``` Scala
>     case other => throw new Exception(s"Musit: Undefined StorageType:$other")
> 
>     // case "rootNode" => RootNode
> ```

remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala, line 19 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0Uua7Ea73se-LuDTm:-KJ0Uua7Ea73se-LuDTn:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala#L19)):_

> ``` Scala
>     // case "rootNode" => RootNode
>   }
>   // implicit val format: Format[StorageUnitType] = Json.format[StorageUnitType]
> ```

remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala, line 28 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0UwDU4UPqHHyJ4ej9:-KJ0UwDU4UPqHHyJ4ejA:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala#L28)):_

> ``` Scala
> object StUnit extends StorageUnitType
> 
> //object RootNode extends StorageUnitType
> ```

remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala, line 92 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0V-gNe6JIiRGef_EX:-KJ0V-gNe6JIiRGef_EY:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala#L92)):_

> ``` Scala
>   }
> 
>   /* def postRoot = Action.async(BodyParsers.parse.json) {
> ```

remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala, line 128 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0V0hID_3I2jF-nOT2:-KJ0V0hID_3I2jF-nOT3:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala#L128)):_

> ``` Scala
>   }
> 
>   /*def listRoot(search: Option[MusitSearch]): Action[AnyContent] = Action.async { request =>
> ```

remove

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala, line 56 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0VSXFbfGwC9PfJZOw:-KJ0VSXFbfGwC9PfJZOx:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala#L56)):_

> ``` Scala
>   }
> 
>   /*def find(search: MusitSearch): Future[Seq[StorageUnit]] = {
> ```

remove

---

_[service_storage_admin/conf/local-logback.xml, line 2 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0Vd-CQMf4ziRh1oBx:-KJ0Vd-CQMf4ziRh1oBy:-55521267) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/conf/local-logback.xml#L2)):_

> ``` XML
> <included>
>   <define name="applicationName" value="Time"/>
> ```

Should be called something else

---

_[service_storage_admin/conf/routes, line 9 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0Via_ypkLQzlZOKmu:-KJ0Via_ypkLQzlZOKmv:573344011) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/conf/routes#L9)):_

> ```
> GET     /v1/storageunit/:id/children           no.uio.musit.microservice.storageAdmin.resource.StorageUnitResource.getChildren(id:Long)
> GET     /v1/storageunit                        no.uio.musit.microservice.storageAdmin.resource.StorageUnitResource.listAll
> #GET     /v1/storageunit                        no.uio.musit.microservice.storageAdmin.resource.StorageUnitResource.listRoot(search: Option[no.uio.musit.microservices.common.domain.MusitSearch])
> ```

if its not used and will not be used, remove it

---

_[service_storage_admin/src/it/scala/StorageUnitIntegrationTest.scala, line 1 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0W05nw9h-VmJu_knd:-KJ0W05nw9h-VmJu_kne:-310475618) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/src/it/scala/StorageUnitIntegrationTest.scala#L1)):_

> ``` Scala
> /*
> ```

remove this file? obsolete?

---

_[service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala, line 37 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0WMQN2y9-eFBgK5Da:-KJ0WMQN2y9-eFBgK5Db:-1830279416) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala#L37)):_

> ``` Scala
>     "postCreate a building" in {
>       val makeMyJSon ="""{"id":-1, "storageType":"Building","storageUnitName":"KHM", "links":[]}""" //
>       /* Json.toJson(StorageUnit(-1, "Room", "ROM1", Some(10), Some("1"), None, Some(20),
> ```

remove comment

---

_[service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala, line 70 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0WP1sozFJMyNB2sMs:-KJ0WP1sozFJMyNB2sMt:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala#L70)):_

> ``` Scala
>     }
> 
>     /*
> ```

remove

---

_[service_storage_admin/test/controllers/StorageUnitControllerSpec.scala, line 50 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0WR14xlvEciRZ5W5C:-KJ0WR15a24EAqVNRTJL:-1280936503) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/test/controllers/StorageUnitControllerSpec.scala#L50)):_

> ``` Scala
>     }
> 
>     /*: Long, storageType: String, storageUnitName: String, area: Option[Long],
> ```

remove

---

_[service_storage_admin/test/controllers/StorageUnitControllerSpec.scala, line 71 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0WWb7BxRrP80iweOT:-KJ0WWb8JiM6EbqDJX_I:-1096879052) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/test/controllers/StorageUnitControllerSpec.scala#L71)):_

> ``` Scala
>     "futuretest" in {
>       val testF: Future[Int] = Future {
>         //throw new Exception("Å nei!")
> ```

oh no ... might be another test

---

_[service_storage_admin/test/controllers/StorageUnitControllerSpec.scala, line 78 [r8]](https://reviewable.io:443/reviews/musit-norway/musit/36#-KJ0WSKGfIxOlKAYlNJ7:-KJ0WSKGfIxOlKAYlNJ8:-1672511890) ([raw file](https://github.com/musit-norway/musit/blob/3da7aec54dfc5360296155e50de26d6244e3f521/service_storage_admin/test/controllers/StorageUnitControllerSpec.scala#L78)):_

> ``` Scala
>       val response = Await.ready(testF2, Duration.Inf)
>       println(s"verdi: ${response.value}")
>       /*
> ```

remove if not needed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/36)_

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:

``` diff

Issues
======
- Added 128


Complexity increasing per file
==============================
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  6
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  21
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnitType.scala  5
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  4
- common/src/main/scala/no/uio/musit/microservices/common/extensions/PlayExtensions.scala  3


Clones added
============
- service_storage_admin/test/controllers/StorageUnitControllerSpec.scala  1
- service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  4
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  5
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala  5
- service_musit_thing/src/it/scala/MusitThing_TestSuite.scala  17

```

See the complete overview on [Codacy](https://www.codacy.com/app/klaus-myrseth/musit/pullRequest?prid=246351&bid=3326252)

**Comment by jarlah** [comment]
Reviewed 10 of 10 files at r9.
Review status: all files reviewed at latest revision, 28 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/36)_

**Pull request merged**
