### PR TITLE
Musark 115

### PR DESCRIPTION
**Pull request by jarlestabell**
I wrote some thoughts about Future[Either[MusitError, T]] in the no.uio.musit.microservices.common.util.Misc.scala file, it doesn't belong in that file, but something like this probably belong somewhere in our documentation, in order to not make people freak out when they first see (flat)Mapping on Future[Either[MusitError, T]]. :)

---

This change is [Reviewable](https://reviewable.io/reviews/musit-norway/musit/51)

### CODE REVIEW

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 48
           

Complexity increasing per file
==============================
- common/src/main/scala/no/uio/musit/microservices/common/utils/DaoHelper.scala  4
- common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  1
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  4
         

Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  -2
         

Clones added
============
- service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  5
         

Clones removed
==============
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=252370&bid=3342773)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:

``` diff

Issues
======
+ Solved 18
- Added 48


Complexity increasing per file
==============================
- common/src/main/scala/no/uio/musit/microservices/common/utils/DaoHelper.scala  4
- common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  1
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  4


Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  -2


Clones added
============
- service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  5


Clones removed
==============
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  -2

```

See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=252370&bid=3342773)

**Comment by jarlah** [comment]
Jarle: du og jeg må ta et møte og gå igjennom all koden relatert til storage admin og se på hva som kan forenkles. Vi bruker codacy sine 500+ code style warnings som utgangspunkt, og sorterer på pakkenavn slik at vi kan gå igjennom de filene som er relevante for denne PR og forrige PR's.

<details><summary>

<i>Previously, musit-project (MUSIT Admin user) wrote…</i></summary>



> Codacy Here is an overview of what got changed by this pull request:
> 
> ``` diff
> 
> Issues
> ======
> + Solved 18
> - Added 48
> 
> 
> Complexity increasing per file
> ==============================
> - common/src/main/scala/no/uio/musit/microservices/common/utils/DaoHelper.scala  4
> - common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  1
> - common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  4
> 
> 
> Complexity decreasing per file
> ==============================
> + service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  -2
> 
> 
> Clones added
> ============
> - service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  5
> 
> 
> Clones removed
> ==============
> + service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  -2
> 
> ```
> 
> See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=252370&bid=3342773)
> 
> </details>

---

Reviewed 4 of 9 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[common/src/main/scala/no/uio/musit/microservices/common/utils/DaoHelper.scala, line 37 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/51#-KJiqwc7mTzBfawr5SmQ:-KJiqwc7mTzBfawr5SmR:302653766) ([raw file](https://github.com/musit-norway/musit/blob/620de6a4d7e79a996f29ce125c7fb6cbcaa98169/common/src/main/scala/no/uio/musit/microservices/common/utils/DaoHelper.scala#L37)):_

> ``` Scala
>    * If it is 1, 1 is returned. Else an appropriately failed future us returned.
>    */
>   def onlyAcceptOneUpdatedRecord(dbio: DBIO[Int]): DBIO[Int] = {
> ```

Jeg må ombestemme meg her. Tittet oppover i bruken av denne funksjonen og exception er ikke håndtert utenom errorhandler. Det er ikke bra kode å kaste exceptions som håndteres av jvm, play eller errorhandler. Så her må vi refaktorere.

---

_[service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala, line 128 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/51#-KJissAzYVSwuPUotXJh:-KJissAzYVSwuPUotXJi:1136147102) ([raw file](https://github.com/musit-norway/musit/blob/620de6a4d7e79a996f29ce125c7fb6cbcaa98169/service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala#L128)):_

> ``` Scala
>     val updateStorageUnitOnlyAction = (updateStorageUnitAction(id, storageUnitAndRoom._1) |> DaoHelper.onlyAcceptOneUpdatedRecord)
> 
>     val combinedAction = updateStorageUnitOnlyAction.flatMap { _ => updateRoomOnlyAction(id, storageUnitAndRoom._2.copy(id = Some(id))) }
> ```

codacy complains about un-named variable. So this should be refactored anyway.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/51#-:-KJitdeZHc93pQBu3ZPk:-195807579)_

**Comment by jarlah** [comment]
Merging, but we will have a meeting where we go through code quality on all of the code in StorageUnitAdmin service

**Pull request merged**
