### PR TITLE
Musark 140

### PR DESCRIPTION
**Pull request by ellenjo**
This change is [Reviewable](https://reviewable.io/reviews/musit-norway/musit/58)

### CODE REVIEW

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 4
           

Complexity increasing per file
==============================
- service_event/app/no/uio/musit/microservice/event/service/EventService.scala  6
- service_event/app/no/uio/musit/microservice/event/domain/EventType.scala  9
- service_event/app/no/uio/musit/microservice/event/dao/EventDao.scala  2
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  3
         

Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  -3
         

Clones added
============
- service_event/app/no/uio/musit/microservice/event/dao/EventDao.scala  1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=259844&bid=3365450)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 4
           

Coverage increased per file
===========================
+ common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  15
+ common/src/main/scala/no/uio/musit/microservices/common/linking/dao/LinkDao.scala  14
         

Coverage decreased per file
===========================
- common/src/main/scala/no/uio/musit/microservices/common/utils/ErrorHelper.scala  -41
- common/src/main/scala/no/uio/musit/microservices/common/domain/MusitError.scala  -1
         

Complexity increasing per file
==============================
- service_event/app/no/uio/musit/microservice/event/service/EventService.scala  6
- service_event/app/no/uio/musit/microservice/event/resource/EventResource.scala  3
- service_event/app/no/uio/musit/microservice/event/domain/EventType.scala  9
- service_event/app/no/uio/musit/microservice/event/dao/EventDao.scala  2
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  3
         

Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  -3
         

Clones added
============
- service_event/app/no/uio/musit/microservice/event/dao/EventDao.scala  1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=259844&bid=3365450)

**Comment by jarlah** [comment]
@jarlestabell and @ellenjo please take a look at https://www.codacy.com/app/musit-project/musit/pullRequest?prid=259844 .. and fix all issues that can be fixed.

**Comment by jarlah** [comment]
Reviewed 9 of 18 files at r1, 3 of 10 files at r2, 1 of 4 files at r5, 5 of 8 files at r6, 2 of 2 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/58)_

**Pull request merged**
