### PR TITLE
Musark 118

### PR DESCRIPTION
**Pull request by ellenjo**
This change is [Reviewable](https://reviewable.io/reviews/musit-norway/musit/47)

### CODE REVIEW

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 30
- Added 133
           

Complexity increasing per file
==============================
- common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  8
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  11
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  14
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  8
         

Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  -10
         

Clones added
============
- common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  2
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  2
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  2
- common/src/main/scala/no/uio/musit/microservices/common/extensions/PlayExtensions.scala  2
         

Clones removed
==============
+ service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  -3
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  -2
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=250059&bid=3336206)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 36
- Added 133
           

Complexity increasing per file
==============================
- common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  6
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  9
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  8
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  8
         

Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  -10
         

Clones added
============
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  2
- common/src/main/scala/no/uio/musit/microservices/common/extensions/PlayExtensions.scala  2
         

Clones removed
==============
+ service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  -3
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  -5
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=250059&bid=3336206)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 35
- Added 134
           

Complexity increasing per file
==============================
- common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  6
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  9
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  8
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  8
         

Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  -10
         

Clones added
============
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  2
- common/src/main/scala/no/uio/musit/microservices/common/extensions/PlayExtensions.scala  2
         

Clones removed
==============
+ service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  -3
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  -5
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=250059&bid=3336206)

**Comment by jarlah** [comment]
This is how it should have been, and which is much much more easy to reason about. But given the fact that we could not land on an agreement, I hereby document this approach in this PR, for future reference.

``` scala
  def updateStorageTripleByID(id: Long, triple: StorageUnitTriple): Future[Either[MusitError, MusitStatusMessage]] = {
    val success = MusitStatusMessage("Record was updated!")
    val numRowsMisMatch = (num: Int) => MusitError(
      status = Status.INTERNAL_SERVER_ERROR,
      message = "Could not update storage unit",
      developerMessage = "# updated rows: " + num
    )
    StorageUnitDao.getStorageType(id).flatMap {
      case Some(storageUnitTypeInDatabase) =>
        if (triple.storageKind == storageUnitTypeInDatabase) {
          triple.storageKind match {
            case StUnit =>
              StorageUnitDao.updateStorageUnit(id, triple.storageUnit).map {
                case 1 =>
                  Right(success)
                case num =>
                  Left(numRowsMisMatch(num))
              }
            case Building =>
              StorageUnitDao.updateBuildingByID(
                id,
                triple.storageUnit,
                triple.getBuilding
              ).map(_ => Right(success))
            case Room =>
              StorageUnitDao.updateRoom(
                id,
                triple.storageUnit,
                triple.getRoom
              ).map(_ => Right(success))
          }
        } else {
          Future.successful(Left(storageUnitTypeMismatch(id, triple.storageKind, storageUnitTypeInDatabase)))
        }
      case None =>
        Future.successful(Left(storageUnitNotFoundError(id)))
    }
  }
```

**Comment by jarlah** [comment]
Reviewed 2 of 8 files at r1, 2 of 6 files at r4, 3 of 14 files at r5, 2 of 8 files at r7, 6 of 7 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/47)_

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:

``` diff

Issues
======
+ Solved 30
- Added 103


Complexity increasing per file
==============================
- common/src/main/scala/no/uio/musit/microservices/common/utils/ServiceHelper.scala  6
- common/src/main/scala/no/uio/musit/microservices/common/utils/ResourceHelper.scala  9
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  8
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  8


Complexity decreasing per file
==============================
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/resource/StorageUnitResource.scala  -10


Clones added
============
- service_storage_admin/app/no/uio/musit/microservice/storageAdmin/dao/StorageUnitDao.scala  2
- common/src/main/scala/no/uio/musit/microservices/common/extensions/PlayExtensions.scala  2


Clones removed
==============
+ service_storage_admin/src/it/scala/no/uio/musit/microservice/storage_admin/resource/StorageUnitIntegrationTest.scala  -4
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/service/StorageUnitService.scala  -5

```

See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=250059&bid=3336206)

**Comment by jarlah** [comment]
Reviewed 4 of 4 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/47)_

**Pull request merged**
