### PR TITLE
Musark 124

### PR DESCRIPTION
**Pull request by klausmyrseth**
This change is [Reviewable](https://reviewable.io/reviews/musit-norway/musit/52)

### CODE REVIEW

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 23
- Added 6
           

Complexity increasing per file
==============================
- service_musit_thing/app/no/uio/musit/microservice/musitThing/resource/MusitThingResource_V1.scala  8
         

Clones added
============
- gui/app/components/organization/OrganizationContainer.js  2
- gui/app/containers/example-view/index.js  1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=254212&bid=3349025)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 23
- Added 6
           

Coverage increased per file
===========================
+ service_geo_location/app/no/uio/musit/microservice/geoLocation/service/GeoLocationService.scala  100
+ common/src/main/scala/no/uio/musit/microservices/common/linking/domain/Link.scala  100
+ common/src/main/scala/no/uio/musit/microservices/common/linking/dao/LinkDao.scala  87
+ common/src/main/scala/no/uio/musit/microservices/common/linking/LinkService.scala  50
         

Complexity increasing per file
==============================
- service_musit_thing/app/no/uio/musit/microservice/musitThing/resource/MusitThingResource_V1.scala  8
         

Clones added
============
- gui/app/components/organization/OrganizationContainer.js  2
- gui/app/containers/example-view/index.js  1
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=254212&bid=3349025)

**Comment by jarlah** [comment]
Reviewed 24 of 26 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/52)_

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:

``` diff

Issues
======
+ Solved 35
- Added 7


Complexity increasing per file
==============================
- service_musit_thing/app/no/uio/musit/microservice/musitThing/resource/MusitThingResource_V1.scala  2


Clones added
============
- gui/app/components/organization/OrganizationContainer.js  2
- gui/app/containers/example-view/index.js  1


Clones removed
==============
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala  -5
+ service_musit_thing/app/no/uio/musit/microservice/musitThing/resource/MusitThingResource_V1.scala  -2

```

See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=254212&bid=3349025)

**Comment by jarlah** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/52)_

**Pull request merged**
