### PR TITLE
Musark 199

### PR DESCRIPTION
**Pull request by sveigl**
This change is [Reviewable](https://reviewable.io/reviews/musit-norway/musit/94)

### CODE REVIEW

**Comment by jarlah** [comment]
burde kanskje ta en titt på codacy og sjekke hvorfor den viser adde 16 når det bare er 1 clone og 2 complexy issues den forteller eksplisitt om. Men ikke veldig viktig, siden vi har noe å jobbe med på den fronten (codacy nøyaktighet)

---

Reviewed 1 of 5 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_[service_event/app/no/uio/musit/microservice/event/dao/ObservationSpritDao.scala, line 41 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFSJVQ_tMFgBXPMLxT:-KOFSJVQ_tMFgBXPMLxU:-1281556050) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/dao/ObservationSpritDao.scala#L41)):_

> ``` Scala
>   protected val dbConfig = DatabaseConfigProvider.get[JdbcProfile](Play.current)
> 
>   private val TilstandTable = TableQuery[TilstandTable]
> ```

det er på tide å bruke engelsk. kan ikke fortsette å bruke norsk i koden. Blir helt feil. Hvis det er mulig finn et engelsk begrep som matcher "tilstand".

---

_[service_event/app/no/uio/musit/microservice/event/domain/Event.scala, line 132 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFSaIJc1mNiDkEzw2g:-KOFSaIJc1mNiDkEzw2h:205174103) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/domain/Event.scala#L132)):_

> ``` Scala
> }
> 
> // ---------------------------------------------------
> ```

Sånne kommentarer er unødvendige. Gir ingen ny kontekst enn det man kan lese i koden, at det er Tilstand og ObservationSpiritDto (!) som er definert her.

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 114 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFSnCMlZM-aBITBtP-:-KOFSnCMlZM-aBITBtP0:-1410575628) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L114)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationRenhold
> ```

som sagt dette gir ingen ny mening, og finn engelsk begrep

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 128 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFSymqqiDIv21RWhQy:-KOFSymqqiDIv21RWhQz:-664567288) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L128)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationGass
> ```

som over

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 142 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFSzgoOJz2zAbzl0Q5:-KOFSzgoOJz2zAbzl0Q6:-664567288) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L142)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationMugg
> ```

som over

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 156 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFT-EgYY98Z4SaS9WI:-KOFT-EhnP80bWMd38Of:-664567288) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L156)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationTyveriSikring
> ```

som over

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 170 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFT-hPjPGoO0UxgvEi:-KOFT-hPjPGoO0UxgvEj:-664567288) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L170)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationBrannSikring
> ```

som over

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 184 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFT0hXO35W0OaczDH6:-KOFT0hXO35W0OaczDH7:-664567288) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L184)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationSkallSikring
> ```

som over

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 198 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFT1FNEZ1vfQri4sil:-KOFT1FNEZ1vfQri4sim:-664567288) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L198)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationVannskadeRisiko
> ```

som over

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 212 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFT1tXgAi8jFDonaYb:-KOFT1tXgAi8jFDonaYc:-664567288) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L212)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationSkadedyr
> ```

som over

---

_[service_event/app/no/uio/musit/microservice/event/service/Observations.scala, line 239 [r2]](https://reviewable.io:443/reviews/musit-norway/musit/94#-KOFT8GpMLEY9q2qg-Id:-KOFT8GqLoFWzi9yzRyY:530177071) ([raw file](https://github.com/musit-norway/musit/blob/b9d5a900e358e20c5414e3686ca7acd7f6c9b051/service_event/app/no/uio/musit/microservice/event/service/Observations.scala#L239)):_

> ``` Scala
> 
> // ------------------------------------------------------------
> //  ObservationSprit
> ```

som over ... egentlig resten av tjenesten .. all kode må være engelsk.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/94#-:-KOFTf0C80piT2AMHhRS:-894282420)_

**Comment by jarlestabell** [comment]
Kjapp kommentar om engelsk vs norsk. Ellen og jeg ble enige for en tid tilbake om å bruke norsk på hendelsestypene som vi ikke har korrekte/"offisielel" engelske termer på ennå.
Dette fordi vi tenkte det da ble tydeligere at navngivningen ikke er i mål ennå.
Line jobber med å få tak i korrekte engelske termer.

**Comment by jarlah** [comment]
Hadde vært helt greit å bruke norsk men da syns jeg det på type/klasse nivå burde vært enten norsk eller engelsk. For eks ObservasjonSkadedyrDto osv. Slik at man ikke får to språk i samme klassenavn. Men det er ikke viktig det er bare forstyrrende. Ikke noe dere behøver å ta tak i nå mao med mindre dere er enige med meg om å bruke samme språk

**Comment by musit-project** [comment]
Reviewed 1 of 5 files at r2, 6 of 10 files at r3, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/94)_

**Comment by jarlah** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r3, 9 of 18 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/94#-:-KOPHJZhEglGajLE4c7h:bnfp4nl)_

**Pull request merged**
