### PR TITLE
Musark 137

### PR DESCRIPTION
**Pull request by jarlestabell**
This change is [Reviewable](https://reviewable.io/reviews/musit-norway/musit/53)

### CODE REVIEW

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 4
           

Clones removed
==============
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala  -3
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=254562&bid=3350116)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 4
           

Coverage decreased per file
===========================
- common/src/main/scala/no/uio/musit/microservices/common/domain/MusitError.scala  -14
         

Clones removed
==============
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala  -5
         
```


See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=254562&bid=3350116)

**Comment by musit-project** [comment]
Codacy Here is an overview of what got changed by this pull request:

``` diff

Issues
======
+ Solved 7
- Added 4


Coverage decreased per file
===========================
- common/src/main/scala/no/uio/musit/microservices/common/domain/MusitError.scala  -14


Clones removed
==============
+ service_storage_admin/app/no/uio/musit/microservice/storageAdmin/domain/StorageUnit.scala  -5

```

See the complete overview on [Codacy](https://www.codacy.com/app/musit-project/musit/pullRequest?prid=254562&bid=3350116)

**Comment by jarlah** [comment]
Reviewed 2 of 5 files at r3, 1 of 3 files at r4, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/musit-norway/musit/53)_

**Pull request merged**
